version: '2'
services:
  wiki2:
      image: 'nickstenning/mediawiki'
      ports:
          - "8880:80"
      links:
          - db:database
      volumes:
          - /data/wiki2:/data
      restart: always

  db:
      image: "mysql:5.7.5"
      expose:
          - "3306"
      environment:
          - MYSQL_ROOT_PASSWORD=defaultpass
      restart: always
